### ISSUE TITLE
Make the docker-compose be able to run without having to build components locally

### ISSUE THREAD

**Issue by kwhetstone** [jenkinsci/custom-distribution-service#101]
The Dockerfile for the backend requires that you build the app locally before being able to use the tool.  This means you'll have to update the backend to be built as part of an intermediate container.  The frontend container should also be built like this too so people don't have to install node and other tools simply to run a tool.

**Comment by sladyn98** [comment]
Closed https://github.com/jenkinsci/custom-distribution-service/pull/104
