### ISSUE TITLE
Community Configuration link leads to 404 Not Found

### ISSUE THREAD

**Issue by martinda** [jenkinsci/custom-distribution-service#111]
When I visit the http://localhost:3001/communityConfiguration there is one "sample-empty.yml" configuration. When I select it, it show the content as 404 Not Found. I should show some minimalist content, like:
```yaml
# This is an empty configuration
```

**Comment by sladyn98** [comment]
https://github.com/jenkinsci/custom-distribution-service/pull/112 @martinda Fixed
