### ISSUE TITLE
Provide a few community samples

### ISSUE THREAD

**Issue by martinda** [jenkinsci/custom-distribution-service#113]
The `sample-empty.yml` is not an empty configuration. I think there needs to be couple of examples:

* an empty one (not very useful but serves as a placeholder)
* a minimalist one (the smallest one that works - without any optional sections)
* the smallest one that has all the optional sections ("one" of everything there can be)

Maybe even the yaml schema could be used as an example.

**Comment by sladyn98** [comment]
Added these.
There are no optionals currently since we removed the casc section.
