### ISSUE TITLE
update center dumped to console is too much

### ISSUE THREAD

**Issue by martinda** [jenkinsci/custom-distribution-service#122]
When I run the application (specifically PR #105), the content of the update center is dumped to the console. This is subjective but it's too much. Can you find a way to display just the start and end? Of have log levels?

**Comment by sladyn98** [comment]
@martinda I do not find any place in the code where the update center is being dumped to the console or logged, is it default spring behavior ?

**Comment by martinda** [comment]
Maybe [this line](https://github.com/jenkinsci/custom-distribution-service/pull/105/files#diff-50722513f6866e41c0ee2001e82608dfR42)?

**Comment by sladyn98** [comment]
Should I just take it out. I remember in one of the reviews I was told to keep it
