### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/custom-distribution-service#20]
- [ ]  Add Project page links [jenkins.io]

- [ ]  Add gitter chat link and CI badges.

- [ ] Add design doc and proposal links

- [ ] Add a quick How to Run guide

**Comment by kwhetstone** [comment]
I think you could even have a copy of this a the end of each milestone to make sure your Readme is accurate for each major release.  When we create Milestone 2 tasks the week of 29 June, we'll make sure to create a copy of this issue at that time.
