### ISSUE TITLE
Prepare for Jenkins Phase 1 Presentation

### ISSUE THREAD

**Issue by kwhetstone** [jenkinsci/custom-distribution-service#24]
As part of the Jenkins GSoC milestones, there's a series of presentations and short demos.  It's a great time to talk about what your project is, what you've accomplished during coding phase 1.  If there's a lot of research you had to do for the project, include that in this phase 1 presentation too. We can go over this on the Tuesday meeting before the demo to give pointers and give you a chance to practice.

Note: this is something we'll copy to all other milestones, and is one of the last tasks for coding phase 1.

What you need:

- [x] Create a short slide presentation to give about your work in Phase 1
- [x] Prepare a demo of the custom distribution service as it exists at the end of Phase 1
- [x] Optional: blog post about GSoC experience
- [ ] Share the demo with interested stakeholders

**Comment by sladyn98** [comment]
The preparation for the demo is complete. 
Here is the link to the slides: https://docs.google.com/presentation/d/1IPF6FUAIQXeBbcJ5v7btJns4-s4lAh-2epKFMrmRycU/edit?usp=sharing
The readme is also up-to date, I think this issue is safe to close.
