### ISSUE TITLE
Retrieve plugin list from update center

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/custom-distribution-service#4]
This feature would involve downloading the plugin lists from https://updates.jenkins.io/current/update-center.json.

**Comment by sladyn98** [comment]
Challenges:
- [ ] The file is 2MB, I do not think we should pull it on every reload, maybe cache it on the browser side.And pull it every few hours. I am not too sure where are we going to store it maybe a redis cache or something along those lines 

- [ ] Also the data is not purely JSON so we have to get rid of the `updateCenter.post(` which is at the start because otherwise it just throws a JSON Parsing error.

**Comment by kwhetstone** [comment]
1) Yes, cache it and do something like a "nightly refresh" to stay current.  Reloading and cashe management should be it's own ticket.  And honestly, running efficiently can be move to Phase 2.  Let's just open a ticket and not assign it to any milestone yet, so you can pull it into milestone 1 or push to milestone 2

**Comment by sladyn98** [comment]
Might have a cron job and that work could be addressed later, just getting it working for now should be enough.

**Comment by sladyn98** [comment]
Closed via https://github.com/jenkinsci/custom-distribution-service/pull/31
