### ISSUE TITLE
Add feature to filter plugins.

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/custom-distribution-service#9]
We could go with something similar to the plugin site in maybe building the ability to filter plugins based on most relevant, maybe most used etc.

**Comment by kwhetstone** [comment]
This might be fairly easy to do in React (in fact, I know it's easy!) but I think the priority is minimally the 2nd part of phase 1.  We'll try to use plugins.io as the inspiration for this UI to keep a sort-of-related look-and-feel.  Also, we should look at the reports coming out of the hackathons from this week.  There might be some pieces that we can visually adapt too.

**Comment by sladyn98** [comment]
@kwhetstone I think this can be safely moved to phase 2 since it just involves filtering the plugins and the search has already been implemented

**Comment by sladyn98** [comment]
Look for inspiration on the plugin site

**Comment by sladyn98** [comment]
Completed
