### ISSUE TITLE
Hosting the Service

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/custom-distribution-service#93]
The service is now self-hosted do we want to proceed with hosting on jenkins infra ?

**Comment by sladyn98** [comment]
Post in Jenkins Infra Mailing List:

**Comment by martinda** [comment]
How is this going? Do you have the link to the posting in the infra mailing list?

**Comment by sladyn98** [comment]
Already sent this out on the infra mailing list

**Comment by sladyn98** [comment]
https://issues.jenkins-ci.org/browse/INFRA-2700: Issue tracking progress

**Comment by sladyn98** [comment]
https://customize.jenkins.io/ 🎉
